config/routes.rb
TestImg::Application.routes.draw do

  resources :images, :only => [:create, :new]

  get ':id' => 'images#show', :as => 'show_image'

  root :to => "welcome#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :title, :presence => true, :length => { :minimum => 3 }
  validates :url, :presence => true, :length => { :minimum => 10 }

  before_save :ensure_uid

  private

    def ensure_uid
      if uid.blank?
        allowed_symbols = ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a
        self.uid = (0...5).collect { allowed_symbols[Kernel.rand(allowed_symbols.length)] }.join
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params[:image])
    if @image.save
      redirect_to root_url, :notice => 'Image created successfully.'
    else
      render :action => :new
    end
  end

  def show
    @image = Image.find_by_uid params[:id]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @images = Image.find :all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_image.html.erb
<p>
  <%= link_to image.title, show_image_path(image.uid) %>
  <br />
  <%= link_to image_tag(image.url, :height => 100, :width => 100), show_image_path(image.uid) %>
</p>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/new.html.erb
<%= form_for @image do |f| %>
  <div><%= f.error_messages %></div>
  <p>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/images/show.html.erb
<h1><%= @image.title %></h1>

<p><%= image_tag(@image.url) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestImg</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div>
    <%= link_to 'Home', root_path %>
  </div>
  <div id="messages">
    <% if flash[:notice].present? %>
      <div id="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert].present? %>
      <div id="alert"><%= flash[:alert] %></div>
    <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div>
  <%= link_to 'Add new image', new_image_path %>
</div>

<div>
  <%= render @images %>
</div>